project:
  type: website

website:
  title: "Website"
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Home
      - Publications.qmd
      - Crafts.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

