project:
  type: website

website:
  title: "Hayley"
  site-url: https://hayley.stagg.phd
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Home
      - Publications.qmd
      - Crafts.qmd
      - href: cv.pdf
        text: CV

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

