---
title: Publications
---

### Pending Publications

#### Rural versus urban out-of-hospital cardiac arrest outcomes in the North East of England from 2018 - 2019; A retrospective analysis

Owen Finney and Hayley Stagg\
September 2023

### Published Papers 

#### The clinical effectiveness of a falls rapid response service, and sex differences of patients using the service: a cross-sectional study in an English ambulance trust

Karl Charlton, Hayley Stagg and Emma Burrow\
June 2023\
British Paramedic Journal, Volume 8, Number 1, 1 June 2023, pp. 28-33(6)\
<https://doi.org/10.29045/14784726.2023.6.8.1.28>

#### Prognostic value of lactate in out-of-hospital cardiac arrest: a prospective cohort study

Karl Charlton and Hayley Stagg\
April 2022\
Journal of Paramedic Practice 14(4):138-145\
<http://dx.doi.org/10.12968/jpar.2022.14.4.138>

#### Predicting conveyance to the emergency department for older adults who fall

Karl Charlton, Hayley Stagg and Emma Burrow\
April 2022\
Journal of Paramedic Practice 14(4):162-168\
<http://dx.doi.org/10.12968/jpar.2022.14.4.162>

#### Incidence of emergency calls and out-of-hospital cardiac arrest deaths during the COVID-19 pandemic: findings from a cross-sectional study in a UK ambulance service

Karl Charlton, Matthew Limmer and Hayley Moore\
April 2021\
Emergency Medicine Journal 38(6):emermed-2020-210291\
<http://dx.doi.org/10.1136/emermed-2020-210291>

#### Intravenous versus oral paracetamol in a UK ambulance service: a case control study

Karl Charlton, Matthew Limmer and Hayley Moore\
May 2020\
British Paramedic Journal 5(1):1-6\
<http://dx.doi.org/10.29045/14784726.2020.06.5.1.1>
